"""add confidence to wound records

Revision ID: 808a4d1f0f3d
Revises: b00000000001
Create Date: 2026-10-03 13:12:47.161322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '808a4d1f0f3d'
down_revision: Union[str, None] = 'b00000000001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wound_records', sa.Column('confidence', sa.Float(), nullable=True))
    op.alter_column('wounds', 'closed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wounds', 'closed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('wound_records', 'confidence')
    # ### end Alembic commands ###
