"""Initial tables creation

Revision ID: 81e1479850a6
Revises: None
Create Date: 2026-07-12 05:43:11.689822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81e1479850a6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_parts',
    sa.Column('body_part_id', sa.String(length=5), nullable=False),
    sa.Column('body_part_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('body_part_id')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.String(length=10), nullable=False),
    sa.Column('role_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=10), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('nurse',
    sa.Column('user_id', sa.String(length=10), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('patients',
    sa.Column('HN', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=10), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('admit_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('HN')
    )
    op.create_index(op.f('ix_patients_HN'), 'patients', ['HN'], unique=False)
    op.create_table('appointments',
    sa.Column('appointment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('HN', sa.String(length=50), nullable=False),
    sa.Column('nurse_user_id', sa.String(length=10), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('appointment_time', sa.Time(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['HN'], ['patients.HN'], ),
    sa.ForeignKeyConstraint(['nurse_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_table('wounds',
    sa.Column('wound_id', sa.String(length=10), nullable=False),
    sa.Column('HN', sa.String(length=50), nullable=False),
    sa.Column('body_part_id', sa.String(length=5), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['HN'], ['patients.HN'], ),
    sa.ForeignKeyConstraint(['body_part_id'], ['body_parts.body_part_id'], ),
    sa.PrimaryKeyConstraint('wound_id')
    )
    op.create_table('wound_records',
    sa.Column('record_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wound_id', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.String(length=10), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('area_pixel', sa.Integer(), nullable=False),
    sa.Column('area_cm2', sa.Float(), nullable=False),
    sa.Column('record_date', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['wound_id'], ['wounds.wound_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wound_records')
    op.drop_table('wounds')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_patients_HN'), table_name='patients')
    op.drop_table('patients')
    op.drop_table('nurse')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('body_parts')
    # ### end Alembic commands ###
